on:
  push:
    branches:
    - release

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn install
    - name: Compile
      run: yarn run tsc -p ./tsconfig.build.json
    - name: Lint
      run: yarn run lint
    - name: Test
      run: yarn run test:coverage
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests      
    - name: npm publish
      run: |
        LATEST=`npm view . version`
        CURRENT=`cat package.json | jq -r .version`
        if [ "$LATEST" != "$CURRENT" ]
        then
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        fi
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
